plugins:
  - image
  - autosave
  - advlist
  - anchor
  - autolink
  - code
  - hr
  - link
  - lists
  - paste
  - table
  - visualblocks
  - example
image_advtab: true
image_list: "/admin/attaches/gallery.json"
toolbar: styleselect | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image
